In [1]:
import pandas as pd

### Working With <b>JSON</b> Files

In [2]:
pd.read_json("Datasets/train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

 You can load json from the URL also

In [5]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.0413
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.7500
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.9370
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,4.3100
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,1.1600
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,2.6900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.1930
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.2610
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-10-10,1760054402,0.3010

### Working with <b>SQL</b>

In [6]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     ---- ----------------------------------- 1.3/11.9 MB 5.1 MB/s eta 0:00:03
     --------- ------------------------------ 2.9/11.9 MB 6.3 MB/s eta 0:00:02
     --------------- ------------------------ 4.5/11.9 MB 6.6 MB/s eta 0:00:02
     --------------------- ------------------ 6.3/11.9 MB 7.3 MB/s eta 0:00:01
     -------------------------- ------------- 7.9/11.9 MB 7.2 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 7.2 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 7.3 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 7.1 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=0c1464fb34046e3eea3c7f4da3a7adf3abeba376a1e3890e5cf35fe0ff658a0b
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [7]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [ ]:
pd.read_sql_query("SELECT * from city", conn)